### ISSUE TITLE
Why not consider BN for test time calculation

### ISSUE THREAD

**Issue by lxtGH** [feinanshan/FANet#3]
Hi，For fairness comparison, previous work including ICnet. BiSegNet, SFnet report the speed with bn, here you merge bn in conv which results in much higher speed.

**Comment by feinanshan** [comment]
It is a common practice to combine BN layers with their previous Conv layers. And you will find it being very useful when you try to deploy the model into some realistic applications.

By explicitly applying BN layers, FANet-18 achieves ~68 FPS, which is very close to 72fps.

When it comes to "misleading and unfair“ speed comparison, I don't think it is right and fair to directly copy numbers from previous papers.  Instead, as a research paper, I would suggest comparing speeds with the same device and the same DL toolbox, or at least do some speed conversion as in SWIFTNet.

**Comment by lxtGH** [comment]
@feinanshan Hi ! Thanks for your reply. Sorry I misunderstand the the Table IV. I just draw my conclusion according to my experience.  I will check it further~
