### ISSUE TITLE
Features extracted by ResNet are different for BiseNet and FANet

### ISSUE THREAD

**Issue by Eashwar93** [feinanshan/FANet#9]
Thank you for the great work!!

The below lines are from the Resnet model return adapted for FANet

```
feat4 = self.layer1(x)
feat8 = self.layer2(feat4) # 1/8
feat16 = self.layer3(feat8) # 1/16
feat32 = self.layer4(feat16) # 1/32
return feat4, feat8, feat16, feat32
```

The comments specify that feat8, feat16, feat32 are feature maps of  1/8, 1/16, 1/32 of the image size but  the actual sizes are 1/16, 1/32,  1/64. 

I also understand why this is happening . Below is the way we create Resnet18 model for FANet
```
def Resnet18(pretrained=True, norm_layer=None, **kwargs):
    model = ResNet(BasicBlock, [2,2,2,2],[2,2,2,2], norm_layer=norm_layer)
    if pretrained:
        model.init_weight(model_zoo.load_url(model_urls['resnet18']))
    return model
```
which is different from the way we create it in BiseNet
```
def Resnet18(pretrained=False, **kwargs):
    model = ResNet(BasicBlock, [2, 2, 2, 2],[1, 2, 2, 2])
    if pretrained:
        model.init_weight(model_zoo.load_url(model_urls['resnet18']))
    return model
```
The stride value for the first BasicBlock is different. 

Could you please clarify that if the additional down-sampling is intended for the FANet or not. 

Will it be possible for you to share the trained model as well?  I don't have access to good GPUs to train it on Cityscapes dataset. It would be nice if you can share the trained model

**Comment by feinanshan** [comment]
Hi, yes, the additional down-sampling is intended, please refer to Sec.III.C of the paper.

**Comment by Eashwar93** [comment]
@pinghu6 Thanks
